# PUERTO
server.port=8087

# NOMBRE MICROSERVICIO
spring.application.name=ms-pagos

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3307/ms_pagos_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# EUREKA CLIENT
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# OPCIONAL
eureka.instance.prefer-ip-address=true

# LOGS
logging.level.root=INFO